# ==================================================================================================
# Copyright (C) 2026 GRAPE Contributors
# ==================================================================================================

# ==================================================================================================
# Function: generate_dependency_graph
#
# Description:
#   Generates a Graphviz DOT file for the enabled module dependency graph and registers a
#   'dep_graph' target to render it to SVG using the 'dot' tool.
#
#   - Modules are clustered by their top-level folder under modules/ (e.g. common, probe, rpi).
#   - Arrows point from a dependent module toward the module it depends on.
#   - Must be called after enumerate_modules() so that ENABLED_MODULES and MODULE_*_PATH /
#     MODULE_*_DEPENDS_ON cache variables are populated.
#
# Parameters:
#   OUTPUT_DIR (optional): Directory to write dep_graph.dot and dep_graph.svg.
#                          Defaults to <binary_dir>/docs.
#
function(generate_dependency_graph)
  cmake_parse_arguments(PARSE_ARGV 0 _ARG "" "OUTPUT_DIR" "")

  if(_ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "generate_dependency_graph: unparsed arguments: ${_ARG_UNPARSED_ARGUMENTS}")
  endif()

  if(NOT _ARG_OUTPUT_DIR)
    set(_ARG_OUTPUT_DIR "${CMAKE_BINARY_DIR}/docs")
  endif()

  get_property(_modules GLOBAL PROPERTY ENABLED_MODULES)
  if(NOT _modules)
    add_custom_target(dep_graph
      COMMAND ${CMAKE_COMMAND} -E cmake_echo_color --yellow
              "dep_graph skipped: ENABLED_MODULES is empty"
      COMMENT "Skipping dependency graph rendering"
      VERBATIM)
    message(STATUS "generate_dependency_graph: ENABLED_MODULES is empty — dep_graph target is a no-op")
    return()
  endif()

  # ------------------------------------------------------------------------------------------------
  # Derive group (top-level folder under modules/) for every enabled module
  set(_groups "")
  foreach(module IN LISTS _modules)
    cmake_path(RELATIVE_PATH MODULE_${module}_PATH
               BASE_DIRECTORY "${CMAKE_SOURCE_DIR}/modules"
               OUTPUT_VARIABLE _rel)
    string(FIND "${_rel}" "/" _slash_pos)
    if(_slash_pos GREATER_EQUAL 0)
      string(SUBSTRING "${_rel}" 0 ${_slash_pos} _group)
    else()
      set(_group "${_rel}")
    endif()
    set(_module_group_${module} "${_group}")
    list(APPEND _groups "${_group}")
  endforeach()
  list(REMOVE_DUPLICATES _groups)
  list(SORT _groups)

  # ------------------------------------------------------------------------------------------------
  # Colour palette — indexed slots: node-fill  node-border  cluster-bg  cluster-border  font-colour
  # Groups are assigned a slot by cycling through in sorted order
  set(_pal_0 "#aecde3" "#2a7ab0" "#e8f3fa" "#2a7ab0" "#153d58")  # blue
  set(_pal_1 "#a8dfd4" "#1f9180" "#e6f7f5" "#1f9180" "#104840")  # teal
  set(_pal_2 "#f5d49a" "#c07820" "#fdf3e0" "#c07820" "#5a3800")  # amber
  set(_pal_3 "#cfb3e8" "#7030b8" "#f3edfb" "#7030b8" "#3a1060")  # purple
  set(_pal_4 "#b8dea8" "#3a8c20" "#ecf7e8" "#3a8c20" "#1a4a0c")  # green
  set(_pal_5 "#f0b8b8" "#b83020" "#fdecea" "#b83020" "#601010")  # red
  set(_num_palette_slots 6)

  # Assign one slot to each group (sorted order, wrapping around)
  set(_group_idx 0)
  foreach(group IN LISTS _groups)
    math(EXPR _slot "${_group_idx} % ${_num_palette_slots}")
    set(_group_pal_${group} "${_pal_${_slot}}")
    math(EXPR _group_idx "${_group_idx} + 1")
  endforeach()

  # ------------------------------------------------------------------------------------------------
  # Build DOT source
  set(_dot "digraph grape_modules {\n")
  string(APPEND _dot "  // Generated by generate_dependency_graph() — do not edit by hand\n\n")
  string(APPEND _dot "  graph [\n")
  string(APPEND _dot "    rankdir     = \"TB\"\n")
  string(APPEND _dot "    bgcolor     = \"#ffffff\"\n")
  string(APPEND _dot "    fontname    = \"Helvetica Neue, Helvetica, Arial, sans-serif\"\n")
  string(APPEND _dot "    fontsize    = 15\n")
  string(APPEND _dot "    fontcolor   = \"#222222\"\n")
  string(APPEND _dot "    label       = \"Module Dependency Graph\"\n")
  string(APPEND _dot "    labelloc    = t\n")
  string(APPEND _dot "    labeljust   = c\n")
  string(APPEND _dot "    pad         = 0.8\n")
  string(APPEND _dot "    splines     = curved\n")
  string(APPEND _dot "    nodesep     = 0.55\n")
  string(APPEND _dot "    ranksep     = 1.1\n")
  string(APPEND _dot "    concentrate = true\n")
  string(APPEND _dot "  ]\n\n")
  string(APPEND _dot "  node [\n")
  string(APPEND _dot "    shape    = box\n")
  string(APPEND _dot "    style    = \"filled,rounded\"\n")
  string(APPEND _dot "    fontname = \"Helvetica Neue, Helvetica, Arial, sans-serif\"\n")
  string(APPEND _dot "    fontsize = 11\n")
  string(APPEND _dot "    margin   = \"0.22, 0.11\"\n")
  string(APPEND _dot "    penwidth = 1.5\n")
  string(APPEND _dot "  ]\n\n")
  string(APPEND _dot "  edge [\n")
  string(APPEND _dot "    arrowhead = vee\n")
  string(APPEND _dot "    arrowsize = 0.75\n")
  string(APPEND _dot "    penwidth  = 1.2\n")
  string(APPEND _dot "    color     = \"#607080\"\n")
  string(APPEND _dot "    style     = solid\n")
  string(APPEND _dot "  ]\n\n")

  # Cluster subgraph per group
  foreach(group IN LISTS _groups)
    set(_pal "${_group_pal_${group}}")
    list(GET _pal 0 _fill)
    list(GET _pal 1 _border)
    list(GET _pal 2 _bg)
    list(GET _pal 3 _cborder)
    list(GET _pal 4 _font)

    string(APPEND _dot "  subgraph cluster_${group} {\n")
    string(APPEND _dot "    label     = \"${group}\"\n")
    string(APPEND _dot "    style     = \"filled, rounded\"\n")
    string(APPEND _dot "    fillcolor = \"${_bg}\"\n")
    string(APPEND _dot "    color     = \"${_cborder}\"\n")
    string(APPEND _dot "    penwidth  = 2\n")
    string(APPEND _dot "    fontname  = \"Helvetica Neue, Helvetica, Arial, sans-serif\"\n")
    string(APPEND _dot "    fontsize  = 12\n")
    string(APPEND _dot "    fontcolor = \"${_font}\"\n")
    string(APPEND _dot "    margin    = 14\n")
    string(APPEND _dot "    node [ fillcolor = \"${_fill}\" color = \"${_border}\" fontcolor = \"${_font}\" ]\n")
    foreach(module IN LISTS _modules)
      if(_module_group_${module} STREQUAL group)
        string(APPEND _dot "    \"${module}\"\n")
      endif()
    endforeach()
    string(APPEND _dot "  }\n\n")
  endforeach()

  # Dependency edges (A -> B: A depends on B); colour matches the source group
  string(APPEND _dot "  // Dependency edges: arrow tip points at the dependency\n")
  foreach(module IN LISTS _modules)
    set(_pal "${_group_pal_${_module_group_${module}}}")
    list(GET _pal 1 _edge_color)
    foreach(dep IN LISTS MODULE_${module}_DEPENDS_ON)
      if(dep IN_LIST _modules)
        string(APPEND _dot "  \"${module}\" -> \"${dep}\" [ color = \"${_edge_color}\" ]\n")
      endif()
    endforeach()
  endforeach()

  string(APPEND _dot "}\n")

  # ------------------------------------------------------------------------------------------------
  # Write DOT at configure time and register dep_graph target for SVG rendering
  file(MAKE_DIRECTORY "${_ARG_OUTPUT_DIR}")
  set(_dot_file "${_ARG_OUTPUT_DIR}/dep_graph.dot")
  set(_svg_file "${_ARG_OUTPUT_DIR}/dep_graph.svg")

  file(WRITE "${_dot_file}" "${_dot}")
  message(STATUS "Dependency graph DOT: ${_dot_file}")

  find_program(GRAPHVIZ_DOT_EXECUTABLE dot NO_CACHE)
  if(GRAPHVIZ_DOT_EXECUTABLE)
    add_custom_target(dep_graph
      COMMAND "${GRAPHVIZ_DOT_EXECUTABLE}" -Tsvg -o "${_svg_file}" "${_dot_file}"
      BYPRODUCTS "${_svg_file}"
      WORKING_DIRECTORY "${_ARG_OUTPUT_DIR}"
      COMMENT "Rendering dependency graph SVG: ${_svg_file}"
      VERBATIM)
  else()
    add_custom_target(dep_graph
      COMMAND ${CMAKE_COMMAND} -E cmake_echo_color --yellow
              "dep_graph skipped: 'dot' executable (graphviz) not found"
      COMMENT "Skipping dependency graph rendering (graphviz not found)"
      VERBATIM)
    message(STATUS "generate_dependency_graph: 'dot' (graphviz) not found — dep_graph target is a no-op")
  endif()
endfunction()
