//=================================================================================================
// Copyright (C) 2026 GRAPE Contributors
//=================================================================================================

#include <array>
#include <bit>
#include <cmath>
#include <cstddef>
#include <cstring>
#include <filesystem>
#include <numbers>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "catch2/catch_approx.hpp"
#include "catch2/catch_test_macros.hpp"
#include "grape/splat/file_io.h"
#include "grape/splat/splat.h"

namespace {

using Catch::Approx;
using grape::splat::Splat;

// NOLINTBEGIN(cppcoreguidelines-avoid-magic-numbers)

//-------------------------------------------------------------------------------------------------
auto toBytes(std::string_view text) -> std::vector<std::byte> {
  const auto bytes = std::as_bytes(std::span{ text });
  return { bytes.begin(), bytes.end() };
}

//-------------------------------------------------------------------------------------------------
template <typename T>
void append(std::vector<std::byte>& data, const T& value) {
  const auto bytes = std::as_bytes(std::span{ &value, 1 });
  data.insert(data.end(), bytes.begin(), bytes.end());
}

//-------------------------------------------------------------------------------------------------
auto makeTestSplats() -> std::vector<Splat> {
  return {
    {
        .position = { .x = 1.F, .y = -2.F, .z = 3.5F },
        .scale = { .x = 0.1F, .y = 0.2F, .z = 0.3F },
        .rotation = grape::splat::fromAxisAngle({ .x = 1.F, .y = 1.F, .z = 0.F }, 0.7F),
        .color = { .r = 10, .g = 128, .b = 250, .a = 200 },
    },
    {
        .position = { .x = -0.25F, .y = 0.F, .z = 100.F },
        .scale = { .x = 1.F, .y = 1.F, .z = 0.001F },
        .rotation = { .w = 1.F, .x = 0.F, .y = 0.F, .z = 0.F },
        .color = { .r = 255, .g = 0, .b = 1, .a = 255 },
    },
  };
}

//-------------------------------------------------------------------------------------------------
TEST_CASE(".splat encoding round trips", "[file_io]") {
  const auto splats = makeTestSplats();
  const auto data = grape::splat::encodeSplat(splats);
  REQUIRE(data.size() == splats.size() * grape::splat::SPLAT_RECORD_SIZE);

  const auto decoded = grape::splat::decodeSplat(data);
  REQUIRE(decoded.has_value());
  REQUIRE(decoded->size() == splats.size());
  for (auto i = 0UZ; i < splats.size(); ++i) {
    const auto& expected = splats.at(i);
    const auto& actual = decoded->at(i);
    // position and scale are stored losslessly
    CHECK(std::bit_cast<std::array<float, 3>>(actual.position) ==
          std::bit_cast<std::array<float, 3>>(expected.position));
    CHECK(std::bit_cast<std::array<float, 3>>(actual.scale) ==
          std::bit_cast<std::array<float, 3>>(expected.scale));
    CHECK(actual.color == expected.color);
    // rotation is quantised to 8 bits. q and -q are equivalent.
    const auto dot = std::abs(
        (actual.rotation.w * expected.rotation.w) + (actual.rotation.x * expected.rotation.x) +
        (actual.rotation.y * expected.rotation.y) + (actual.rotation.z * expected.rotation.z));
    CHECK(dot == Approx(1.F).margin(1e-3));
  }
}

//-------------------------------------------------------------------------------------------------
TEST_CASE(".splat decoder rejects partial records", "[file_io]") {
  const auto data = std::vector<std::byte>(grape::splat::SPLAT_RECORD_SIZE + 1);
  CHECK_FALSE(grape::splat::decodeSplat(data).has_value());
  CHECK(grape::splat::decodeSplat({}).value().empty());
}

//-------------------------------------------------------------------------------------------------
TEST_CASE("PLY decoder reads 3DGS training output", "[file_io]") {
  // Property order and types as written by the reference 3DGS implementation, with an extra
  // unused property and a leading element to exercise offset computation
  auto data = toBytes(
      "ply\n"
      "format binary_little_endian 1.0\n"
      "comment generated by test\n"
      "element camera 1\n"
      "property double fx\n"
      "element vertex 2\n"
      "property float x\nproperty float y\nproperty float z\n"
      "property float nx\nproperty float ny\nproperty float nz\n"
      "property float f_dc_0\nproperty float f_dc_1\nproperty float f_dc_2\n"
      "property float f_rest_0\n"
      "property float opacity\n"
      "property float scale_0\nproperty float scale_1\nproperty float scale_2\n"
      "property float rot_0\nproperty float rot_1\nproperty float rot_2\nproperty float rot_3\n"
      "property uchar extra\n"
      "end_header\n");
  append(data, 500.0);  // camera
  const auto write_vertex = [&data](std::array<float, 18> values) {
    for (const auto value : values) {
      append(data, value);
    }
    append(data, std::uint8_t{ 42 });
  };
  //            x    y     z     nx  ny  nz  dc0  dc1    dc2     rest opac sc0  sc1    sc2
  write_vertex({
      1.F,
      2.F,
      3.F,
      0.F,
      0.F,
      0.F,
      0.F,
      1.77F,
      -1.77F,
      9.F,
      0.F,
      0.F,
      -1.F,
      1.F,
      // rot (w x y z), unnormalised
      2.F,
      0.F,
      0.F,
      0.F,
  });
  write_vertex({
      -1.F,
      0.F,
      0.F,
      0.F,
      0.F,
      0.F,
      0.F,
      0.F,
      0.F,
      0.F,
      10.F,
      -2.F,
      -2.F,
      -2.F,
      0.F,
      0.F,
      0.F,
      3.F,
  });

  const auto decoded = grape::splat::decodePly(data);
  REQUIRE(decoded.has_value());
  REQUIRE(decoded->size() == 2);

  const auto& s0 = decoded->at(0);
  CHECK(s0.position.x == Approx(1.F));
  CHECK(s0.position.y == Approx(2.F));
  CHECK(s0.position.z == Approx(3.F));
  CHECK(s0.scale.x == Approx(1.F));
  CHECK(s0.scale.y == Approx(std::exp(-1.F)));
  CHECK(s0.scale.z == Approx(std::numbers::e_v<float>));
  CHECK(s0.rotation.w == Approx(1.F));
  CHECK(s0.color.r == 128);  // 0.5 + SH_C0 * 0
  CHECK(s0.color.g == 255);  // 0.5 + SH_C0 * 1.77 ≈ 0.999
  CHECK(s0.color.b == 0);    // 0.5 - SH_C0 * 1.77 ≈ 0.001
  CHECK(s0.color.a == 128);  // sigmoid(0)

  const auto& s1 = decoded->at(1);
  CHECK(s1.position.x == Approx(-1.F));
  CHECK(s1.rotation.z == Approx(1.F));
  CHECK(s1.color.a == 255);  // sigmoid(10)
}

//-------------------------------------------------------------------------------------------------
TEST_CASE("PLY decoder rejects unsupported or malformed input", "[file_io]") {
  const auto header = [](std::string_view format, std::string_view properties) {
    return toBytes(std::string("ply\nformat ") + std::string(format) + " 1.0\nelement vertex 1\n" +
                   std::string(properties) + "end_header\n");
  };
  static constexpr auto ALL_PROPERTIES =
      "property float x\nproperty float y\nproperty float z\n"
      "property float f_dc_0\nproperty float f_dc_1\nproperty float f_dc_2\n"
      "property float opacity\n"
      "property float scale_0\nproperty float scale_1\nproperty float scale_2\n"
      "property float rot_0\nproperty float rot_1\nproperty float rot_2\nproperty float rot_3\n";

  SECTION("valid header, missing data") {
    CHECK_FALSE(grape::splat::decodePly(header("binary_little_endian", ALL_PROPERTIES)));
  }
  SECTION("ascii format") {
    auto data = header("ascii", ALL_PROPERTIES);
    data.resize(data.size() + (14 * sizeof(float)));
    CHECK_FALSE(grape::splat::decodePly(data));
  }
  SECTION("missing attribute") {
    auto data = header("binary_little_endian", "property float x\n");
    data.resize(data.size() + sizeof(float));
    const auto result = grape::splat::decodePly(data);
    REQUIRE_FALSE(result);
    CHECK(result.error().contains("'y'"));
  }
  SECTION("not a PLY file") {
    CHECK_FALSE(grape::splat::decodePly(toBytes("hello\nworld\n")));
  }
  SECTION("no end of header") {
    CHECK_FALSE(grape::splat::decodePly(toBytes("ply\nformat binary_little_endian 1.0\n")));
  }
  SECTION("unknown type") {
    CHECK_FALSE(grape::splat::decodePly(header("binary_little_endian", "property half x\n")));
  }
}

//-------------------------------------------------------------------------------------------------
TEST_CASE("Splats can be saved and loaded from file", "[file_io]") {
  const auto splats = makeTestSplats();
  const auto path = std::filesystem::temp_directory_path() / "grape_splat_file_io_test.splat";
  REQUIRE(grape::splat::save(path, splats).has_value());
  const auto loaded = grape::splat::load(path);
  std::filesystem::remove(path);
  REQUIRE(loaded.has_value());
  CHECK(loaded->size() == splats.size());
}

//-------------------------------------------------------------------------------------------------
TEST_CASE("Loading reports errors", "[file_io]") {
  CHECK_FALSE(grape::splat::load("does_not_exist.splat").has_value());
  CHECK_FALSE(grape::splat::load("unsupported.xyz").has_value());
}

// NOLINTEND(cppcoreguidelines-avoid-magic-numbers)

}  // namespace
