name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, [self-hosted, ARM64]]
        include:
          - runner: ubuntu-latest
            name: x86_64
          - runner: [self-hosted, ARM64]
            name: aarch64

    name: Build and Test (${{ matrix.name }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch history for versioning
        run: |
          git fetch --unshallow --tags || git fetch --depth=100 --tags

      - name: Install system dependencies and utilities 
        run: |
          chmod +x ./toolchains/install_base.sh
          ./toolchains/install_base.sh

      - name: Install CMake
        run: |
          chmod +x ./toolchains/install_cmake.sh
          ./toolchains/install_cmake.sh

      - name: Install LLVM/Clang toolchain
        run: |
          chmod +x ./toolchains/install_llvm.sh
          ./toolchains/install_llvm.sh

      - name: Set cache directories
        run: |
          echo "CCACHE_DIR=$HOME/.cache/ccache" >> $GITHUB_ENV
          echo "CTCACHE_DIR=$HOME/.cache/ctcache" >> $GITHUB_ENV

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CCACHE_DIR }}
            ${{ env.CTCACHE_DIR }}
          key: grape-${{ runner.arch }}-${{ runner.os }}-cache
          restore-keys: |
            grape-${{ runner.arch }}-${{ runner.os }}-cache

      - name: Configure
        run: cmake --preset clang

      - name: Build
        run: cmake --build build/clang --target all examples tests

      - name: Report ccache stats
        run: ccache -s        

      - name: Run unit tests
        run: cmake --build build/clang --target check

# TODO
# - Setup a self-hosted X86 runner
# - Build for both clang and gcc
# - Fail on linting or formatting errors
# - Setup configuration presets for applications, developer and CI builds
# - After PR is merged and newly tagged, build and generate deployment artifacts (tarball)
# - Introduce sanitizer builds including [RTSan](https://clang.llvm.org/docs/RealtimeSanitizer.html)
